### ISSUE TITLE
[carp_mobile_sensing] batteryLevel is not being updated

### ISSUE THREAD

**Issue by luciamontesinos** [cph-cachet/carp.sensing-flutter#257]
The `batteryLevel` is not being updated.  Is there something missing here?: https://github.com/cph-cachet/carp.sensing-flutter/blob/e117f69965f90cefcca0a2318f15546c18938ea7/carp_mobile_sensing/lib/runtime/device_manager.dart#L118-L139

**Comment by bardram** [comment]
Fixed as part of v 0.40.0 (which is available in the `develop` branch).

**Comment by luciamontesinos** [comment]
@bardram This fix does not solve the battery issue. It is still not being updated

**Comment by bardram** [comment]
Should be fixed with 0.40.3
